EscuelaItinerante/Controllers/AlumnoController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using EscuelaItinerante.Models;
using DES.Data.Clases;
using DES.Logic;

namespace EscuelaItinerante.Controllers
{
    public class AlumnoController : Controller
    {
        private AlumnoLogic _alumnoLogic = new AlumnoLogic();
        private ComisionLogic _comisionLogic = new ComisionLogic();


        public AlumnoController()
        {
        }

        [Authorize]
        public ActionResult InscribirAlumno()
        {
            var vm = new InscribirAlumnoViewModel();
            return View(vm);
        }

        [Authorize]
        [HttpPost]
        public ActionResult InscribirAlumno(InscribirAlumnoViewModel model)
        {
            var alumno = _alumnoLogic.GetAlumnoByNroDocumento(model.NroDocumento);

            if (alumno == null)
                ModelState.AddModelError("NroDocumento", "El Nro. de Documento ingresado no existe.");
            else
            {
                model.Comisiones = _comisionLogic.GetComisiones((int)model.Sede).OrderBy(x => x.Curso.ToString()).ThenBy(x => x.Coordinador.ToString()).ToList();
                model.Alumno = alumno;
            }

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult FinalizarInscripcion(int idalumno, int idcomision, int arancel, string observacionesdelainscripcion)
        {
            var inscribirAlumnoDTO = new InscripcionAlumnoDTO();
            inscribirAlumnoDTO.IdAlumno = idalumno;
            inscribirAlumnoDTO.IdComision = idcomision;
            inscribirAlumnoDTO.ObservacionesDeLaInscripcion = observacionesdelainscripcion;
            inscribirAlumnoDTO.Arancel = arancel;

            bool inscripcionExitosa = _alumnoLogic.InscribirAlumnoComision(inscribirAlumnoDTO);

            return Json(inscripcionExitosa, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult CambiarEstadoCursada(int nroDocumento = 0)
        {
            var vm = new CambiarEstadoCursadaViewModel();

            if (nroDocumento != 0)
            {
                vm.Alumno = _alumnoLogic.GetAlumnoByNroDocumento(nroDocumento);
                
                if (vm.Alumno != null)
                    vm.Comisiones = _comisionLogic.GetComisionesDelAlumno(vm.
                        Alumno.IdAlumno);
            }

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        public ActionResult CambiarEstadoCursada(int idAlumno, int idComision, int nuevoestadocursada)
        {
            bool pagoexitoso = _alumnoLogic.CambiarEstadoCursada(idAlumno, idComision, (EstadoCursada)nuevoestadocursada);

            return Json(pagoexitoso, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult NuevoAlumno()
        {
            var vm = new NuevoAlumnoViewModel();
            return View(vm);
        }
        
        [HttpPost]
        public ActionResult NuevoAlumno(NuevoAlumnoViewModel model)
        {
            var alumnoInscripto = _alumnoLogic.GetAlumnoByNroDocumento(model.NroDocumento);

            if (alumnoInscripto != null)
                ModelState.AddModelError("NroDocumento", "El alumno ya se encuenta inscripto en el instituto");

            if (model.CodigoPostal == 0)
                ModelState["CodigoPostal"].Errors.Clear();
            
            if (model.Hijos == 0)
                ModelState["Hijos"].Errors.Clear();

            if (ModelState.IsValid)
            {
                var alumno = new Alumno();
                alumno.Nombre = model.Nombre;
                alumno.Apellido = model.Apellido;
                alumno.Tipodoc = model.Tipodoc;
                alumno.NroDocumento = model.NroDocumento;
                alumno.Direccion = model.Direccion ?? string.Empty;
                alumno.CodigoPostal = model.CodigoPostal;
                alumno.Localidad = model.Localidad ?? string.Empty;
                alumno.Telefono = model.Telefono ?? string.Empty;
                alumno.Celular = model.Celular ?? string.Empty;
                alumno.Email = model.Email;
                alumno.ComoNosConocio = model.ComoNosConocio ?? string.Empty;
                alumno.EstadoCivil = model.EstadoCivil;
                alumno.Hijos = model.Hijos;
                alumno.EstudiosRealizados = model.EstudiosRealizados ?? string.Empty;
                alumno.ConocidoEnInstituto = model.ConocidoEnInstituto ?? string.Empty;
                alumno.Observaciones = model.Observaciones ?? string.Empty;
                _alumnoLogic.NuevoAlumno(alumno);

                return RedirectToAction("NuevoAlumnoExitoso");
            }

            return View(model);
        }

        public ActionResult BuscarAlumno()
        {
            var vm = new BuscarAlumnoViewModel();
            return View(vm);
        }

        [HttpPost]
        public ActionResult BuscarAlumno(BuscarAlumnoViewModel model)
        {
            model.Alumnos = _alumnoLogic.GetAlumnosByFiltro(model.CadenaABuscar);
            return View(model);
        }

        public ActionResult FichaAlumno(int idAlumno)
        {
            var vm = new FichaAlumnoViewModel();
            vm.Alumno = _alumnoLogic.GetAlumnoByID(idAlumno);

            if (vm.Alumno != null)
                vm.Comisiones = _comisionLogic.GetComisionesDelAlumno(vm.Alumno.IdAlumno);

            return View(vm);
        }


        public ActionResult NuevoAlumnoExterno()
        {
            var vm = new NuevoAlumnoViewModel();
            return View(vm);
        }

        public ActionResult NuevoAlumnoExitoso()
        {
            return View();
        }


    }
}

EscuelaItinerante/Controllers/ReporteController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using EscuelaItinerante.Models;
using DES.Logic;
using DES.Data.Clases;

namespace EscuelaItinerante.Controllers
{
    [Authorize]
    public class ReporteController : Controller
    {
        private AlumnoLogic _alumnoLogic = new AlumnoLogic();
        private ComisionLogic _comisionLogic = new ComisionLogic();
        private PagoLogic _pagoLogic = new PagoLogic();

        public ReporteController()
        {
            
        }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ComisionesTodas()
        {
            var vm = new ComisionesTodasViewModel();
            vm.Comisiones = _comisionLogic.GetComisiones();
            return View(vm);
        }

        public ActionResult AlumnosTodos()
        {
            var vm = new AlumnosTodosViewModel();
            return View(vm);
        }

        public ActionResult Pagos()
        {
            var vm = new PagosViewModel();
            return View(vm);
        }

        [HttpPost]
        public ActionResult Pagos(PagosViewModel model)
        {
            model.Pagos = _pagoLogic.GetPagos((Sede)model.IdSede, model.FechaDesde, model.FechaHasta);
            return View(model);
        }

        public ActionResult AlumnosPorCurso()
        {
            var vm = new AlumnosPorCursoViewModel();
            return View(vm);
        }

        [HttpPost]
        public ActionResult AlumnosPorCurso(AlumnosPorCursoViewModel model)
        {
            model.Alumnos = _alumnoLogic.GetAlumnosByComision(model.IdComision);
            return View(model);
        }

    }
}

EscuelaItinerante/Views/Shared/UsuarioNoAutorizado.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Usted no se encuentra loggeado.</h2>

EscuelaItinerante/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aplicación de Escuela Itinerante de Psicología Social</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datatable")
    <link href="~/Content/DataTable/jquery.dataTables.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatable")
    <script src="~/Scripts/sitio.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="~/Images/icon.ico" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Denver", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Alumnos<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("NuevoAlumno", "Alumno" )">Nuevo Alumno</a></li>
                                <li><a href="@Url.Action("BuscarAlumno", "Alumno" )">Buscar Alumno</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("InscribirAlumno", "Alumno" )">Inscribir Alumno a Curso</a></li>
                                <li><a href="@Url.Action("CambiarEstadoCursada", "Alumno" )">Cambiar estado de cursada</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pagos<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("PagoClase", "Pago" )">Nuevo Pago</a></li>
                                <li><a href="@Url.Action("PagoParcial", "Pago" )">Nuevo Pago Parcial</a></li>
                                @*<li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("NuevoPago", "Pago")">Nuevo Pago</a></li>*@
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reportes <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("AlumnosPorCurso", "Reporte" )">Alumnos por cursos</a></li>
                                <li><a href="@Url.Action("Pagos", "Reporte" )">Pagos</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("AlumnosTodos", "Reporte")">Todos los Alumnos</a></li>
                            </ul>
                        </li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr class="col-md-12"/>
        <footer class="col-md-12">
            <p>&copy; @DateTime.Now.Year - Desarrollado por mazcui</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>